Update fitgen.yml

diff --git a/.github/workflows/fitgen.yml b/.github/workflows/fitgen.yml
--- a/.github/workflows/fitgen.yml
+++ b/.github/workflows/fitgen.yml
@@ -15,9 +15,12 @@ jobs:
       - name: Check PR comment
         id: check-comment
         run: |
-          echo "trigger=${{ contains(github.event.comment.body, 'run fitgen') }}" >> $GITHUB_OUTPUT
-          if [[ "$a" =~ ^run\ fitgen\ ([0-9]+\.[0-9]+)$ ]]; then
+          echo "trigger=${{ startWith(github.event.comment.body, 'run fitgen') }}" >> $GITHUB_OUTPUT
+          if [[ "${{ github.event.comment.body }}" =~ ^run\ fitgen\ ([0-9]+\.[0-9]+)$ ]]; then
             echo "sdkversion=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+          else 
+            echo "comment syntax error"
+            exit 1
           fi
 
       - name: Checkout PR
